# Builds the AIPage browser extension (codeberg.org/dasmatus/aipage) from a
# pinned `main` source rev and produces the unpacked `dist-firefox` /
# `dist-chrome` store dirs that nix/home/{librewolf,brave}.nix consume.
#
# Why fetchGit + an in-flake build (not a flake input, not the old local
# tarball): aipage's own flake only exposes an *impure* `apps.build` (it shells
# out to `bun install` + `bunx`), and its built `dist-*` dirs are gitignored —
# so no flake input can reach a built artifact. `builtins.fetchGit` with a
# pinned `rev` is a content-addressed eval-time FOD: pure under `nix flake
# check`, baked into the ISO closure at build time, and cache-hit on the live
# ISO (the installer substitutes the prebuilt dists from the ISO store — no
# network, no source build at install time). The old design used a
# `file://$HOME/.local/share/aipage/dist-firefox.tar` FOD that only existed on
# the dev machine, so `nixos-install` on the ISO failed to evaluate.
#
# The build re-implements aipage's `xtask build` pipeline (xtask/src/main.rs)
# in bash rather than running `cargo run -p xtask`: it gives hard failures on
# missing tools (xtask silently skips CSS/wasm-opt), writes directly to `$out`
# (xtask writes into the read-only workspace root), and skips compiling xtask.
# Keep this in step with xtask when aipage's pipeline changes; the update
# script (scripts/update-aipage.sh) warns on xtask drift.
#
# Vendoring: cargo deps via `rustPlatform.fetchCargoVendor` (Cargo.lock is v4,
# no git deps — only intra-workspace path deps, which live in `aipageSrc` and
# are found via the workspace layout by `cargoSetupHook`); JS deps
# (postcss/tailwind/autoprefixer) via bun2nix's `fetchBunDeps` + `hook`, which
# populates `node_modules` offline from a nix-store cache. `sass` uses
# `pkgs.dart-sass` directly (the `sass` npm package pulls `sass-embedded`,
# which fetches a native binary in a postinstall — avoided).
{
  pkgs,
  rustPlatform,
}:
let
  # Pin: codeberg.org/dasmatus/aipage main. Bump via scripts/update-aipage.sh.
  aipageRev = "944064e01a58f9f9e0c0e76c91aea17f6ce269b1";
  aipageSrc = builtins.fetchGit {
    url = "https://codeberg.org/dasmatus/aipage.git";
    ref = "main";
    rev = aipageRev;
  };

  # Workspace version (manifests share it). Pure-eval readFile of a fetchGit
  # store path is allowed (it's a store path, not a mutable local path input).
  aipageVersion =
    (builtins.fromTOML (builtins.readFile "${aipageSrc}/Cargo.toml")).workspace.package.version;

  # wasm-bindgen-cli's version MUST exactly equal the `wasm-bindgen` crate
  # resolved in aipage's Cargo.lock (currently 0.2.125): the CLI refuses to
  # process a .wasm built with a different crate version. nixpkgs ships an
  # older CLI, so build the matched one from fetchCrate (recipe + hashes
  # reused from aipage's own flake.nix). The update script asserts the lock
  # version still matches.
  wasmBindgenVersion = "0.2.125";
  wasm-bindgen-cli = pkgs.rustPlatform.buildRustPackage {
    pname = "wasm-bindgen-cli";
    version = wasmBindgenVersion;
    src = pkgs.fetchCrate {
      pname = "wasm-bindgen-cli";
      version = wasmBindgenVersion;
      hash = "sha256-zRawtjxMOdTMX+mZaiNR3YYfTiZJhf9qj7kXSSeMxrc=";
    };
    cargoHash = "sha256-aZCfgR23Qb0Pn4Mm4ToMtuuRQqSJjXCR9li/VvP5CTM=";
    doCheck = false;
    nativeBuildInputs = [ pkgs.gcc ];
  };

  # Vendored registry crates for the whole workspace (sidebar/background/
  # content + their shared crates + xtask). Intra-workspace path deps are part
  # of `aipageSrc` and are NOT re-vendored. `hash` is refreshed by the update
  # script via the lib.fakeHash → "got:" sha256 loop.
  cargoDeps = rustPlatform.fetchCargoVendor {
    src = aipageSrc;
    hash = "sha256-f0S2yAu9pn/sjpZECbo8G4tTIRDDKz3jfiyWH9BC3ek=";
  };

  # Vendored JS deps for the CSS step (postcss-cli + tailwind + autoprefixer).
  # `bun.nix` is generated by `bun2nix -l bun.lock -o nix/aipage-bun.nix` and
  # carries the per-package fetchurl hashes from aipage's bun.lock, so
  # `fetchBunDeps` takes no `hash` argument here.
  bunDeps = pkgs.bun2nix.fetchBunDeps { bunNix = ./aipage-bun.nix; };

  # The target-shared dist: 3 wasm bundles (bindgen + wasm-opt) + CSS + static
  # assets. Built once; the per-target wrappers below copy this and add the
  # target manifest, so the wasm isn't built twice.
  aipageDistCommon = pkgs.stdenv.mkDerivation {
    pname = "aipage-dist-common";
    version = aipageVersion;
    src = aipageSrc;

    nativeBuildInputs = [
      pkgs.cargo
      pkgs.rustc
      rustPlatform.cargoSetupHook
      pkgs.llvmPackages.lld # wasm32-unknown-unknown linker (nixpkgs rustc
      # delegates wasm linking to the system `lld`, not a self-contained
      # rust-lld — without this, `cargo build --target wasm32-…` fails with
      # "linker `lld` not found").
      wasm-bindgen-cli
      pkgs.binaryen # `wasm-opt`
      pkgs.bun
      pkgs.bun2nix.hook # reads `bunDeps`, populates node_modules offline
      pkgs.dart-sass # `sass` binary — replaces `bunx sass`
    ];

    inherit cargoDeps bunDeps;

    # Point the wasm32 target at the nix-store lld explicitly (belt-and-
    # suspenders alongside lld being on PATH via nativeBuildInputs).
    CARGO_TARGET_WASM32_UNKNOWN_UNKNOWN_LINKER = "${pkgs.llvmPackages.lld}/bin/lld";

    # Mirrors xtask's `build(target)`: cargo build the 3 wasm crates →
    # wasm-bindgen each (sidebar=web ES module, background/content=no-modules)
    # → wasm-opt -Oz -all → CSS → copy the shared static assets. The
    # per-target manifest is added by `mkTarget`.
    buildPhase = ''
      runHook preBuild

      mkdir -p "$out"

      cargo build --release --target wasm32-unknown-unknown \
        -p aipage-sidebar -p aipage-background -p aipage-content

      for c in sidebar background content; do
        case "$c" in
          sidebar) bt=web ;;
          *) bt=no-modules ;;
        esac
        wasm-bindgen \
          "target/wasm32-unknown-unknown/release/aipage_$c.wasm" \
          --out-dir "$out" --out-name "$c" --target "$bt" --no-typescript
        wasm-opt -Oz -all "$out/''${c}_bg.wasm" -o "$out/''${c}_bg.wasm"
      done

      sass assets/sidebar.scss "$out/sidebar.css" --style=compressed --no-source-map
      bunx postcss assets/tailwind.css -o "$out/tailwind.css"

      cp assets/sidebar.html assets/sidebar_loader.js \
         assets/background_loader.js assets/content_loader.js \
         assets/anti_cheat.js "$out/"

      runHook postBuild
    '';

    dontInstall = true; # buildPhase writes directly to $out
  };

  # Per-target wrapper: the shared dist + the target manifest as manifest.json.
  # `passthru.manifest` exposes the parsed manifest at eval time so consumers
  # can derive the gecko id / version without hardcoding (and without a build).
  mkTarget =
    target: manifestFile:
    pkgs.runCommand "aipage-${target}-${aipageVersion}"
      {
        passthru = {
          inherit aipageSrc aipageVersion;
          manifest = builtins.fromJSON (builtins.readFile "${aipageSrc}/assets/${manifestFile}");
        };
      }
      ''
        mkdir -p "$out"
        cp -r "${aipageDistCommon}/." "$out/"
        cp "${aipageSrc}/assets/${manifestFile}" "$out/manifest.json"
      '';
in
{
  firefox = mkTarget "firefox" "manifest.firefox.json";
  chrome = mkTarget "chrome" "manifest.chrome.json";
}
