# Assembles the Quickshell config directory: the checked-in QML under qml/,
# plus a Theme.qml generated from rust/palette.json.
#
# Generating rather than hand-writing the palette keeps rust/palette.json the
# one place colours are defined, the way nix/home/beamenu.nix already reads it
# with builtins.fromJSON and the Rust crates read it with include_str!. A
# hand-copied QML palette would be a sixth source of truth, which is the exact
# problem docs/superpowers/specs/2026-08-23-system-palette-single-source-design.md
# exists to stop.
#
# Split out of default.nix as a plain function so flake/packages.nix can build
# the same tree for the qmllint gate. A home-manager module cannot be
# evaluated from the flake's package set, but this can.
#
# Neutrals, fonts and metrics are baked in at build time. The accent is not:
# wallpaper-tui derives it from the current wallpaper and rewrites
# tint/current.json, which Theme.qml watches, so a wallpaper change repaints
# the shell with no home-manager switch.
{
  pkgs,
  stateHome,
}:
let
  inherit (pkgs) lib;

  palette = builtins.fromJSON (builtins.readFile ../../../rust/palette.json);

  # Double-quoted, not an indented string: Nix strips the common indentation
  # off a '' '' literal, which would flatten every one of these to column 0.
  colorProperties = lib.concatStringsSep "\n" (
    lib.mapAttrsToList (
      name: value: "    readonly property color ${name}: \"${value}\";"
    ) palette.colors
  );

  # Named Theme, not Palette: QtQuick already exports a Palette type, and a
  # singleton of that name resolves to QQuickPalette instead of this one, so
  # every Theme.bg would silently read a property that does not exist.
  themeQml = ''
    pragma Singleton

    // Generated by nix/home/quickshell/tree.nix from rust/palette.json.
    // Edit the JSON, not this file: this one is rebuilt on every switch.
    //
    // QtQuick is imported for the `color` property type, which is a QtQuick
    // basic type rather than a Quickshell one.
    import QtQuick
    import Quickshell
    import Quickshell.Io

    Singleton {
    ${colorProperties}

        readonly property string fontUi: "${palette.fonts.ui}";
        readonly property string fontMono: "${palette.fonts.mono}";
        readonly property int fontSize: ${toString palette.fonts.size};

        // Bar geometry, kept beside the colours for the same reason the
        // launcher's metrics are: waybar's stylesheet had them as CSS
        // literals, which is where a "why is this 30 and that 32" afternoon
        // comes from.
        readonly property int barHeight: ${toString palette.bar.height};
        readonly property int barSpacing: ${toString palette.bar.spacing};
        readonly property int barFontSize: ${toString palette.bar.fontSize};
        readonly property int barPillPadding: ${toString palette.bar.pillPadding};
        readonly property int barIconSize: ${toString palette.bar.iconSize};
        readonly property int barTitleMaxWidth: ${toString palette.bar.titleMaxWidth};

        // Alpha suffixes are applied at the seam by each consumer, so they stay
        // strings here rather than being folded into the colours above.
        readonly property string alphaPanel: "${palette.alpha.panel}";
        readonly property string alphaHeading: "${palette.alpha.heading}";

        readonly property color accentFallback: "${palette.accentFallback}";

        // Quickshell's qmltypes gives FileView.adapter the type FileViewAdapter
        // without exporting it, so qmllint cannot resolve anything reached
        // through it. The bindings work; only the linter is blind, so the
        // category is suppressed here rather than across the whole tree.
        // qmllint disable unresolved-type

        // A missing file, an unreadable one and a null accent all land on the
        // fallback. The shell has to paint before any wallpaper has ever been
        // set, which is the state a fresh install boots into.
        readonly property color accent: {
            const live = tintState.adapter.root?.accent;
            return live ? live : accentFallback;
        }

        FileView {
            id: tintState

            path: "${stateHome}/wallpaper-tui/tint/current.json"
            watchChanges: true
            onFileChanged: reload()
            adapter: JsonAdapter { }
        }
        // qmllint enable unresolved-type
    }
  '';

  themeFile = pkgs.writeText "Theme.qml" themeQml;

  # Quickshell finds singletons by scanning for `pragma Singleton` and needs no
  # qmldir. qmllint does need one: without the declaration it types `Theme` as
  # the component rather than the instance, so every Theme.bg reads as a
  # missing property and the warnings that matter get lost in the noise.
  qmldirFile = pkgs.writeText "qmldir" ''
    singleton Theme 1.0 Theme.qml
  '';
in
pkgs.runCommand "dots-quickshell-config" { } ''
  mkdir -p "$out"
  cp -r ${./qml}/. "$out/"
  chmod -R u+w "$out"
  cp ${themeFile} "$out/Theme.qml"
  cp ${qmldirFile} "$out/qmldir"
''
