// Pins Chrome.qml's implicitHeight contract. Two review rounds on task 1
// had to measure this by hand before anything here caught it: `body` has
// to be a ColumnLayout that actually counts its content, not a bare Item
// that silently reports zero, or every caller's `height:
// panel.implicitHeight` goes back to guessing a compensation constant.
//
// Chrome.qml only reaches QtQuick, QtQuick.Layouts and the Theme
// singleton, so qmltestrunner CAN instantiate it directly — the blocker is
// only that the real Theme.qml is generated by tree.nix (a Quickshell
// Singleton pulling in the native plugin qmltestrunner cannot load; see
// tests/README.md). fixtures/theme-stub/ works around that with a plain
// QtQuick singleton stub, and symlinks to the real Chrome.qml/Panel.qml so
// this tests the shipped files themselves, never a copy that could drift.
import QtQuick
import QtQuick.Layouts
import QtTest
import "fixtures/theme-stub/common"
import "sourcescan.js" as SourceScan

TestCase {
    id: testCase
    name: "ChromeGeometry"

    function readSource(relPath) {
        const xhr = new XMLHttpRequest();
        xhr.open("GET", Qt.resolvedUrl(relPath), false);
        xhr.send();
        compare(xhr.status, 200, relPath + " must be readable (needs QML_XHR_ALLOW_FILE_READ=1)");
        return xhr.responseText;
    }

    // Comment-stripped source, so a scan sees only real bindings and not
    // prose that happens to mention the same identifier — a comment saying
    // "panel.implicitHeight" must not stand in for the binding using it.
    // sourcescan.js owns the strip; tst_source_scan.qml pins it.
    function readCode(relPath) {
        return SourceScan.stripComments(readSource(relPath));
    }

    Component {
        id: emptyBodyChrome
        Chrome {
            width: 400
            padding: 24
            title: "T"
            hints: [{ key: "a", label: "b" }]
        }
    }

    Component {
        id: taggedBodyChrome
        Chrome {
            width: 400
            padding: 24
            title: "T"
            hints: [{ key: "a", label: "b" }]

            Item {
                Layout.preferredWidth: 100
                Layout.preferredHeight: 300
            }
        }
    }

    Component {
        id: noHintsChrome
        Chrome {
            width: 400
            padding: 24
            title: "T"
            hints: []
        }
    }

    Component {
        id: hugeFlickableChrome
        Chrome {
            width: 400
            padding: 24
            title: "T"
            hints: [{ key: "a", label: "b" }]

            Flickable {
                Layout.fillWidth: true
                Layout.fillHeight: true
                contentWidth: width
                contentHeight: 5000
            }
        }
    }

    Component {
        id: zeroPaddingChrome
        Chrome {
            width: 400
            padding: 0
            title: "T"
            hints: [{ key: "a", label: "b" }]
        }
    }

    Component {
        id: fiftyPaddingChrome
        Chrome {
            width: 400
            padding: 50
            title: "T"
            hints: [{ key: "a", label: "b" }]
        }
    }

    // The regression this exists for: if `body` ever goes back to being a
    // bare Item (as it was before the fix), a child's Layout.preferredHeight
    // is inert — a plain Item does not participate in QtQuick.Layouts — and
    // this delta collapses to 0 instead of 300.
    function test_body_is_a_layout_that_counts_its_content() {
        const empty = createTemporaryObject(emptyBodyChrome, testCase);
        const tagged = createTemporaryObject(taggedBodyChrome, testCase);
        verify(empty !== null);
        verify(tagged !== null);
        compare(tagged.implicitHeight - empty.implicitHeight, 300, "a 300px body child must add exactly 300px to Chrome's implicitHeight");
    }

    // Cheatsheet.qml relies on this directly: its own height formula adds
    // scroll.contentHeight to panel.implicitHeight itself, which is only
    // correct if a Flickable's (arbitrarily large) contentHeight never
    // leaks into implicitHeight the way a ColumnLayout child's
    // Layout.preferredHeight does — a Flickable reports no implicitHeight
    // of its own, and this pins that rather than assuming it.
    function test_flickable_body_contributes_nothing() {
        const empty = createTemporaryObject(emptyBodyChrome, testCase);
        const flick = createTemporaryObject(hugeFlickableChrome, testCase);
        verify(empty !== null);
        verify(flick !== null);
        compare(flick.implicitHeight, empty.implicitHeight, "a Flickable's contentHeight (5000px here) must not leak into Chrome's implicitHeight");
    }

    function test_hidden_footer_costs_nothing() {
        const withHints = createTemporaryObject(emptyBodyChrome, testCase);
        const withoutHints = createTemporaryObject(noHintsChrome, testCase);
        verify(withHints !== null);
        verify(withoutHints !== null);
        verify(withHints.implicitHeight > withoutHints.implicitHeight, "a visible hint footer must add height over an empty hints list");
    }

    function test_padding_is_counted_on_both_edges() {
        const zero = createTemporaryObject(zeroPaddingChrome, testCase);
        const fifty = createTemporaryObject(fiftyPaddingChrome, testCase);
        verify(zero !== null);
        verify(fifty !== null);
        compare(fifty.implicitHeight - zero.implicitHeight, 100, "50px of padding must cost exactly 100px, top and bottom together");
    }

    // --- source-reading: guards the three callers against reintroducing a
    // hardcoded compensation constant instead of Chrome's own
    // implicitHeight — the idiom tst_tint_wiring.qml uses for the same
    // class of bug, a caller silently going unwired while the callee's own
    // tests (above) stay green.
    function test_arrange_height_uses_implicitHeight_not_a_guessed_constant() {
        const src = readCode("../../nix/home/desktop/quickshell/qml/monitors/Arrange.qml");
        verify(src.indexOf("panel.implicitHeight") !== -1, "Arrange.qml's panel height must be derived from Chrome's implicitHeight");
        verify(src.indexOf("+ 96") === -1, "Arrange.qml must not reintroduce the old hardcoded heading/footer compensation constant");
    }

    function test_settings_height_uses_implicitHeight_not_a_guessed_constant() {
        const src = readCode("../../nix/home/desktop/quickshell/qml/settings/Settings.qml");
        verify(src.indexOf("panel.implicitHeight") !== -1, "Settings.qml's panel height must be derived from Chrome's implicitHeight");
        verify(src.indexOf("+ 96") === -1, "Settings.qml must not reintroduce the old hardcoded heading/footer compensation constant");
    }

    function test_cheatsheet_height_uses_implicitHeight_not_a_guessed_constant() {
        const src = readCode("../../nix/home/desktop/quickshell/qml/cheatsheet/Cheatsheet.qml");
        verify(src.indexOf("panel.implicitHeight") !== -1, "Cheatsheet.qml's panel height must be derived from Chrome's implicitHeight");
        verify(src.indexOf("+ 72") === -1, "Cheatsheet.qml must not reintroduce the old hardcoded heading/footer compensation constant");
    }
}
