# ChromaLeon, a GNOME Shell extension that recolors the Shell and
# GTK/libadwaita apps to match the current wallpaper's accent color.
#
# Not from nixpkgs: pkgs.gnomeExtensions.* is generated by
# buildGnomeExtension.nix, which fetches a prebuilt
# extensions.gnome.org/extension-data/<uuid>.v<N>.shell-extension.zip and
# overwrites metadata.json from a base64 blob baked into that generator. There
# is no rev or patch seam in that path, and ChromaLeon's metadata.json carries
# no e.g.o upload version at all, only "version-name" -- so there is nothing at
# that URL to fetch even before the patch below is considered. This follows
# nix/packages/betterbird.nix and nix/packages/aipage.nix instead: an inline
# fetcher with a pinned hash. Not a flake input, matching the repo's uniform
# precedent for a single-consumer source with no upstream flake, and because
# keeping rev, hash and patch in one file makes a version bump and its patch
# reconciliation one reviewable diff rather than a flake.lock entry that can
# drift invisibly against the patch.
#
# stdenvNoCC, not stdenv: everything shipped is JS, CSS and XML copied
# verbatim plus one glib-compile-schemas call. Nothing compiles, so there is no
# reason to pull a C toolchain into the closure the way betterbird.nix and
# claude-desktop.nix must for autoPatchelfHook.
#
# THE PATCH DOES NOT MAKE CHROMALEON RECOLOR PAPIRUS. That was investigated and
# rejected. Its icon engine is a find-and-replace over roughly 24 literal
# Adwaita hex fills; Papirus-Dark shares none of those values, ships no
# scalable/ directory at all (fixed pixel-size dirs, every stanza Type=Fixed),
# and recolors folders by symlinking a pre-drawn named variant rather than
# substituting a fill. Those are different mechanisms, and this repo already
# implements the Papirus one properly in
# nix/home/desktop/quickshell/qml/wallpaper/Icons.qml. Grafting it in here
# would be a second recoloring backend rather than a bugfix, and nothing
# upstream would take. So the patch fixes a real independent bug instead (see
# its own header), and nix/home/base/gnome-extensions.nix pins the icon toggles
# off so the Adwaita-only engine never runs against Papirus-Dark at all.
#
# Bumping: move `rev`, set `hash` to lib.fakeHash, build once to read the real
# value out of the mismatch, then re-check that the patch still applies.
# `patches` fails the build LOUDLY when it does not, which is the point.
{
  lib,
  stdenvNoCC,
  fetchFromGitHub,
  glib,
}:
stdenvNoCC.mkDerivation {
  pname = "gnome-shell-extension-chromaleon";
  version = "2.2.0";

  src = fetchFromGitHub {
    owner = "Fabito02";
    repo = "ChromaLeon";
    rev = "bc9c2631c714cd853f7525d31d834705ad0bedb9";
    hash = "sha256-U3Ql5azysH+PT5xXaehmaCEkR9ETqsq48YlGlgH7J+8=";
  };

  # A behavioral, multi-file fix, so a .patch rather than a postPatch
  # substituteInPlace: it adds an instance field and threads a new function
  # parameter through a call site, neither of which a substitution can express.
  patches = [ ../patches/chromaleon/restore-user-icon-theme.patch ];

  # glib-compile-schemas only, no compiler. The plain `glib` attribute is
  # enough: nativeBuildInputs puts every output of a listed package on PATH,
  # and glib-compile-schemas lives in glib.bin.
  nativeBuildInputs = [ glib ];

  # Nothing to configure or build. The generic phases would no-op anyway with
  # no configure script and no Makefile in the tree, but saying so states the
  # fact rather than leaning on auto-detection to reach the same place.
  dontConfigure = true;
  dontBuild = true;

  installPhase = ''
    runHook preInstall

    # Fail loud on a UUID rename. GNOME Shell requires metadata.uuid to equal
    # the directory name byte for byte and refuses a mismatched pair with no
    # error anyone would ever see -- the extension simply never appears in
    # `gnome-extensions list`. Checking here turns that silent runtime no-op
    # into a build failure that names the problem.
    grep -Fq '"uuid": "user-accent-colors@fabito02"' metadata.json || {
      echo "chromaleon.nix: metadata.json uuid no longer matches" \
           "user-accent-colors@fabito02 -- update the extension directory" \
           "name and gnome-extensions.nix's assumptions to match." >&2
      exit 1
    }

    extDir="$out/share/gnome-shell/extensions/user-accent-colors@fabito02"
    mkdir -p "$extDir"

    # Exactly the file set manage.sh's -zip step ships: `gnome-extensions pack`
    # defaults plus every --extra-source it names. Read out of that script, not
    # guessed. chromaleon.js matters even though extension.js never imports it,
    # because prefs.js does -- omitting it builds fine and breaks only the
    # first time someone opens the Preferences window, as an ImportError with
    # no build-time signal whatsoever.
    cp -r extension.js prefs.js prefs.css metadata.json chromaleon.js \
          schemas utils ui templates assets locale \
          "$extDir/"

    # REQUIRED, and required HERE rather than against the source tree. Without
    # it the gschema stays uncompiled and every settings read in chromaleon.js,
    # extension.js and ui/preferencesPage.js throws on first access; GNOME
    # surfaces that as the extension failing to enable, never as a message
    # naming the missing gschemas.compiled. Compiling the source copy instead
    # of $extDir looks correct at build time and fails at runtime.
    glib-compile-schemas --strict "$extDir/schemas"

    runHook postInstall
  '';

  # REQUIRED: nix/home/base/gnome-extensions.nix derives its dconf
  # enabled-extensions list with `map (e: e.extensionUuid) extensions`, so a
  # package without this breaks that eval for every extension in the file, not
  # just this one.
  passthru.extensionUuid = "user-accent-colors@fabito02";

  meta = {
    description = "Recolor GNOME Shell and GTK/libadwaita apps to match the wallpaper's accent color";
    homepage = "https://github.com/Fabito02/ChromaLeon";
    # Every source file header says GPL-3.0-or-later. The LICENSE file is the
    # plain GPLv3 text, which is normal: the "or later" grant lives in the
    # per-file headers and is what governs.
    license = lib.licenses.gpl3Plus;
    platforms = lib.platforms.linux;
  };
}
