# agenix recipient rules (read by the `agenix` CLI, not by the flake):
# which public keys each .age file is encrypted to. Machines decrypt with
# /etc/ssh/ssh_host_ed25519_key (generated by the ssh-host-key oneshot,
# nix/modules/secrets.nix). Per machine: `cat
# /etc/ssh/ssh_host_ed25519_key.pub`, append it here, then `agenix
# --rekey` so existing secrets re-encrypt for the new recipient set.
let
  # FIXME: replace with this machine's /etc/ssh/ssh_host_ed25519_key.pub
  # after the first `nixos-rebuild switch` generates it.
  hosts = [ ];
in
{
  "gitlab-pat.age".publicKeys = hosts;
}
